---
# tasks file for ansible-role-dmenu

- name: Getting latest dmenu version
  shell: | # noqa 303
    set -o pipefail
    git ls-remote --tags https://git.suckless.org/dmenu | sed 's/.*\///' | egrep "^[0-9]*(\.[0-9]*)(\.[0-9]*)?" | sort | tail -n1
  register: dmenu_git
  changed_when: false

- name: Removing any dmenu package
  become: yes
  package:
    name: dmenu
    state: absent

- name: Checking if dmenu is installed
  stat:
    path: "{{ prefix }}/bin/dmenu"
  register: dmenu_installed

- name: Getting current dmenu version
  shell: |
    set -o pipefail
    "{{ prefix }}/bin/dmenu -v | sed 's/dmenu-//'"
  when: dmenu_installed.stat.exists
  register: dmenu_local
  changed_when: false

- name: Set forced version
  set_fact:
    dmenu_git_version: "{{ dmenu_install_version }}"
  when: dmenu_force_install | bool

- name: Set latest dmenu version
  set_fact:
    dmenu_git_version: "{{ dmenu_git.stdout }}"
  when: not dmenu_force_install

- name: Set local dmenu version
  set_fact:
    dmenu_local_version: "{{ dmenu_local.stdout }}"
  when: dmenu_installed.stat.exists

- include_tasks: uninstall.yml
  when:
    - dmenu_installed.stat.exists
    - (dmenu_git_version != dmenu_local_version) or dmenu_force_install

- include_tasks: install.yml
  when: not dmenu_installed.stat.exists or
        dmenu_force_install or
        (dmenu_git_version != dmenu_local_version)